program = stmt+ exit_stmt ;
stmt = decl_stmt | assign_stmt | if_stmt ;
decl_stmt = ("infect" | "immune") type identifier "💉" expr "⏳" ;
assign_stmt = identifier "💉" expr "⏳" ;
if_stmt = "survive" expr "{" stmt+ "}" [ "perish" "{" stmt+ "}" ] ;
exit_stmt = "exit" expr "⏳" ;
type = "🩸" | "🫀" | "💊" ;
expr = arith_expr [ ("==" | "!=") arith_expr ] ;
arith_expr = term { ("+" | "-") term } ;
term = factor { "*" factor } ;
factor = ["!"] (identifier | constant | boolean) ;
boolean = "alive" | "dead" ;
constant = digit+ ;
identifier = letter { letter | digit | "_" } ;